"""
RetiBoard database module.

Public API for local structural metadata storage.
See database.py for the async SQLite wrapper and models.py for data types.

Spec: §3.1, §3.3, §4
"""

from retiboard.db.models import Board, PostMetadata, ThreadSummary
from retiboard.db.database import (
    open_board_db,
    board_dir,
    board_db_path,
    board_payloads_dir,
    save_board_config,
    load_board_config,
    insert_post,
    get_post,
    get_thread_posts,
    get_catalog,
    get_thread_count,
    post_exists,
    content_hash_exists,
    get_declared_payload_size,
    get_blob_reference,
    delete_chunk_manifests_for_blobs,
    delete_chunk_transfer_state_for_blobs,
    delete_peer_chunk_availability_for_blobs,
    delete_post_metadata,
    delete_thread_metadata,
    get_post_blob_references,
    get_thread_blob_references,
    get_control_state,
    has_control,
    hide_thread,
    unhide_thread,
    hide_post,
    unhide_post,
    mark_post_purged,
    mark_thread_purged,
    mark_expired_threads,
    delete_abandoned_threads,
    enforce_thread_cap,
)

__all__ = [
    "Board",
    "PostMetadata",
    "ThreadSummary",
    "open_board_db",
    "board_dir",
    "board_db_path",
    "board_payloads_dir",
    "save_board_config",
    "load_board_config",
    "insert_post",
    "get_post",
    "get_thread_posts",
    "get_catalog",
    "get_thread_count",
    "post_exists",
    "content_hash_exists",
    "get_declared_payload_size",
    "get_blob_reference",
    "delete_chunk_manifests_for_blobs",
    "delete_chunk_transfer_state_for_blobs",
    "delete_peer_chunk_availability_for_blobs",
    "delete_post_metadata",
    "delete_thread_metadata",
    "get_post_blob_references",
    "get_thread_blob_references",
    "get_control_state",
    "has_control",
    "hide_thread",
    "unhide_thread",
    "hide_post",
    "unhide_post",
    "mark_post_purged",
    "mark_thread_purged",
    "mark_expired_threads",
    "delete_abandoned_threads",
    "enforce_thread_cap",
]
